sources:
  - name: raw
    database: postgres
    schema: raw
    tables:
      - name: facts
      - name: prices

  - name: fmp
    database: postgres
    schema: raw
    tables:
      - name: fmp_earnings